Repository wonjangnimsamgyetang-team3/followingfollower, pull requests merged in 2024-03, with the labels that each got.

#4 [feat/#3] - auth, nonauth 페이지 세팅
  src/app/(auth)/test/page.tsx
  src/app/(nonAuth)/test/page.tsx
Labels: documentation, enhancement

#5 [feat] - axios 세팅
  package.json
  yarn.lock
Labels: documentation, enhancement

#8 [feat/#6] - fullcalendar 불러오기
  package-lock.json
  package.json
  src/app/calendar/page.tsx
  yarn.lock
Labels: documentation, enhancement

#18 [feat] - supabase todos 캘린더에 표시
  database.types.ts
  src/app/calendar/calendar.css
  src/app/calendar/page.tsx
  src/app/globals.css
  src/supabase/supabase.ts
Labels: documentation

#20 [feat/#19] - 이미지 파일 업로드 및 불러오기, 새 todo등록, 등록된 todo 목록을 feed에 불러오기
  package-lock.json
  package.json
  src/app/feed/newTodo/page.tsx
  src/app/feed/page.tsx
  src/components/NewTodo.tsx
  src/components/TodoCard.tsx
  src/components/TodoList.tsx
  src/components/ToggleButton.tsx
  src/icons/HeartFillIcon.tsx
  src/icons/HeartIcon.tsx
  yarn.lock
Labels: documentation, enhancement

#22 [feat/#21] - footer 추가
  src/app/layout.tsx
  src/assets/github-icon.png
  src/assets/youtube-icon.png
  src/components/Footer.tsx
  tailwind.config.ts
Labels: documentation, enhancement

#27 [fea/#26] 마이페이지 내가 쓴 글, 내가 좋아요한 글 ProfileReview.tsx 생성
  database.types.ts
  src/app/(auth)/mypage/page.tsx
  src/app/mypage/page.tsx
  src/app/provider.tsx
  src/app/shared/store.ts
  src/app/types/type.ts
  src/components/ProfileContents.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileReview.tsx
  src/query/mutation.ts
  src/query/queryKey.ts
  src/supabase/myPage/profileImage.ts
  src/supabase/supabase.ts
  tailwind.config.ts
Labels: bug, documentation, enhancement

#29 [rename/#28] - 임시로 만든 캘린더 page, 컴포넌트로 변경
  src/app/(auth)/mypage/page.tsx
  src/components/Calendar.tsx
  src/style/calendar.css
Labels: documentation

#38 [feat/#37] - 메인페이지 전체 글 생성 및 기능 구현
  src/app/main/page.tsx
  src/app/types/type.ts
  src/components/AllCard.tsx
  src/components/NewCard.tsx
Labels: documentation, enhancement

#40 [feat/#39] 마이페이지 - 내가 할 일, 내가 좋아요 한 일 완성
  database.types.ts
  src/app/(auth)/mypage/page.tsx
  src/app/shared/store.ts
  src/app/types/type.ts
  src/components/ProfileContents.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileReview.tsx
  src/components/ProfileReviewLike.tsx
  src/components/ProfileReviewTab.tsx
  src/components/TodoList.tsx
  src/supabase/myPage/profileImage.ts
Labels: documentation, enhancement

#44 [feat/#30] - 서비스 소개 페이지 구성
  database.types.ts
  src/app/about/page.tsx
  src/app/globals.css
  src/assets/boy.png
  src/assets/calendar.png
  src/assets/comment.png
  src/assets/girl.png
  src/assets/memo.png
  src/components/NavBar.tsx
  src/style/calendar.css
  tailwind.config.ts
Labels: documentation, enhancement

#46 [feat/#45] - about 페이지에 팀원 추가 및 next.config images 추가
  next.config.mjs
  src/app/about/page.tsx
  tailwind.config.ts
Labels: documentation, enhancement

#48 [feat/#47] - 메인페이지 배너 추가
  src/app/page.tsx
  src/components/Banner.tsx
  src/components/NavBar.tsx
Labels: documentation, enhancement

#50 [feat/#49] - zustand로 로그인된 유저 정보 관리하기
  middleware.ts
  next.config.mjs
  package.json
  public/profile.png
  src/app/(auth)/test/page.tsx
  src/app/(nonAuth)/join/page.tsx
  src/app/(nonAuth)/login/page.tsx
  src/app/about/page.tsx
  src/app/feed/newTodo/page.tsx
  src/app/page.tsx
  src/app/shared/store.ts
  src/components/LogOut.tsx
  src/components/NavBar.tsx
  src/components/NewTodo.tsx
  src/supabase/supabase.ts
  tailwind.config.ts
  yarn.lock
Labels: documentation, enhancement

#57 [feat/#42] 값 수정 후 마이페이지 - 이미지 수정과 동시에 DB-myPageAccount에 수정한 이미지 저장
  src/app/(auth)/mypage/page.tsx
  src/app/(nonAuth)/join/page.tsx
  src/app/feed/[id]/page.tsx
  src/app/shared/store.ts
  src/app/types/type.ts
  src/components/ProfileContents.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileReview.tsx
  src/components/ProfileReviewLike.tsx
  src/query/queryKey.ts
  src/supabase/myPage/profileImage.ts
  src/util/formmatDate.ts
Labels: documentation, enhancement

#59 [Feat/#58] 마이페이지 - 이미지 버그 해결 ㅎ;; 및 전반적인 기능 구현 완료
  src/app/feed/[id]/page.tsx
  src/components/ProfileContents.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileReview.tsx
  src/components/ProfileReviewLike.tsx
  src/components/ProfileReviewTab.tsx
  src/supabase/myPage/profileImage.ts
Labels: documentation, enhancement

#61 [feat/#60] - todo, 댓글 삭제 기능 완성
  database.types.ts
  package-lock.json
  package.json
  public/image.png
  src/app/(auth)/mypage/page.tsx
  src/app/(nonAuth)/join/page.tsx
  src/app/(nonAuth)/login/page.tsx
  src/app/feed/newTodo/page.tsx
  src/app/feed/page.tsx
  src/app/layout.tsx
  src/app/shared/store.ts
  src/components/LogOut.tsx
  src/components/NewTodo.tsx
  src/components/TodoBar.tsx
  src/components/TodoCard.tsx
  src/components/TodoList.tsx
  src/components/TodoModal/CommentForm.tsx
  src/components/TodoModal/TodoDetail.tsx
  src/components/TodoModal/TodoModal.tsx
  src/util/getLocalStorageJSON.ts
  yarn.lock
Labels: documentation, enhancement

#65 [feat/#53] - 투두리스트에 팔로우 기능 구현 중..
  src/app/feed/page.tsx
  src/components/TodoCard.tsx
Labels: bug, documentation, enhancement

#69 [feat/fix/#62] - 소셜 로그인 정보 불러오기 해결
  middleware.ts
  src/app/(nonAuth)/join/page.tsx
  src/app/(nonAuth)/login/page.tsx
  src/app/feed/[id]/page.tsx
  src/app/feed/newTodo/page.tsx
  src/app/feed/page.tsx
  src/app/main/page.tsx
  src/app/page.tsx
  src/components/NavBar.tsx
Labels: documentation, enhancement

#70 [fix] - test page 삭제
  src/app/(auth)/test/page.tsx
  src/app/(nonAuth)/test/page.tsx
  src/app/test/page.tsx
  src/components/TodoCard.tsx
Labels: bug, documentation

#71 [fix] - 배포 충돌 해결
  src/app/(nonAuth)/join/page.tsx
  src/app/(nonAuth)/login/page.tsx
  src/app/feed/[id]/page.tsx
  src/app/feed/page.tsx
  src/app/main/page.tsx
  src/common/test.ts
  src/components/AllCard.tsx
  src/components/Calendar.tsx
  src/components/LikeTop.tsx
  src/components/LogOut.tsx
  src/components/NewCard.tsx
  src/components/NewTodo.tsx
  src/components/ProfileContents.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileReview.tsx
  src/components/ProfileReviewLike.tsx
  src/components/ProfileReviewTab.tsx
  src/components/TodoCard.tsx
  src/components/TodoModal/CommentForm.tsx
  src/components/TodoModal/TodoDetail.tsx
  src/components/test.tsx
  src/query/mutation.ts
  src/shared/store.ts
  src/supabase/myPage/profileImage.ts
  src/types/todoInCalendar.ts
  src/types/type.ts
Labels: bug

#72 [fix] - 배포 에러 해결 중
  src/app/(auth)/mypage/page.tsx
Labels: bug

#73 [fix] - 배포 에러 해결 중
  src/app/(nonAuth)/login/page.tsx
  src/app/feed/page.tsx
  src/components/ProfileContents.tsx
  src/shared/store.ts
Labels: bug

#74 [fix] - 배포 에러 해결 중 strict:false 설정
  tsconfig.json
Labels: bug

#75 [fix] - 배포 에러 해결 중
  src/components/ProfileImage.tsx
Labels: bug

#76 [fix] - 배포 에러 해결 중
  src/types/type.ts
Labels: bug

#79 [feat/#78] - feed에서 좋아요 순, 최신순으로 todo 정렬
  public/Spinner.svg
  src/app/feed/[id]/page.tsx
  src/app/feed/page.tsx
  src/components/NewTodo.tsx
  src/components/TodoBar.tsx
  src/components/TodoCard.tsx
  src/components/TodoList.tsx
  src/components/TodoModal/CommentForm.tsx
  src/components/TodoModal/TodoDetail.tsx
  src/components/TodoModal/TodoModal.tsx
  src/components/ToggleButton.tsx
Labels: documentation, enhancement

#81 [feat/#80] - todo수정 취소기능 수정, todo수정 글자 수 제한
  src/components/TodoCard.tsx
  src/components/TodoList.tsx
  src/components/TodoModal/TodoDetail.tsx
  tailwind.config.ts
Labels: bug, documentation, enhancement

#83 [fix/#82] store 의 이미지 type 오류 해결
  database.types.ts
  src/app/feed/page.tsx
  src/components/ProfileContents.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileReview.tsx
  src/components/ProfileReviewLike.tsx
  src/components/ProfileReviewTab.tsx
  src/shared/store.ts
  src/supabase/myPage/profileImage.ts
  src/types/type.ts
  tsconfig.json
Labels: bug, documentation, enhancement

#87 [feat/#84] - 비밀번호 찾기 모달창으로 변경
  src/app/(auth)/layout.tsx
  src/app/(auth)/mypage/page.tsx
  src/app/(nonAuth)/join/page.tsx
  src/app/(nonAuth)/layout.tsx
  src/app/(nonAuth)/login/page.tsx
  src/app/feed/newTodo/page.tsx
  src/app/feed/page.tsx
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/page.tsx
  src/app/shared/store.ts
  src/components/FindPassword/PasswordDetail.tsx
  src/components/FindPassword/PasswordModal.tsx
  src/components/FindPassword/PasswordPotal.tsx
  src/components/LogOut.tsx
  src/components/NavBar.tsx
  src/components/NewCard.tsx
  src/components/ProfileReview.tsx
  src/components/Rendering.tsx
  src/components/TodoList.tsx
Labels: documentation, enhancement

#90 [style/#89] - 메인페이지 css작업 및 로고 수정
  src/app/main/page.tsx
  src/app/page.tsx
  src/assets/FF.png
  src/assets/FF2.png
  src/assets/FFlogo.png
  src/components/AllCard.tsx
  src/components/Banner.tsx
  src/components/FindPassword/PasswordDetail.tsx
  src/components/NavBar.tsx
  src/components/NewCard.tsx
  src/types/type.ts
Labels: documentation

#95 [fix/#94] - 코멘트 아바타 이미지에 rounded-full추가, next.config.mjs파일 수정
  middleware.ts
  next.config.mjs
  src/app/feed/newTodo/page.tsx
  src/assets/redSpinner.svg
  src/assets/whiteSpinner.svg
  src/components/Loading.tsx
  src/components/NewTodo.tsx
  src/components/TodoBar.tsx
  src/components/TodoCard.tsx
  src/components/TodoList.tsx
  src/components/TodoModal/CommentForm.tsx
  src/components/TodoModal/TodoDetail.tsx
Labels: bug, documentation, enhancement

#97 [fix/#96] 마이페이지 - ProfileReview의 userTodo 받아서 넘기는 props 타입 수정 / 좋아요 리스트 가져올 때 들어오는 null값에 대한 처리
  src/app/(auth)/mypage/page.tsx
  src/components/ProfileContents.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileReview.tsx
  src/components/ProfileReviewLike.tsx
  src/components/ProfileReviewTab.tsx
Labels: bug, documentation, enhancement

#99 [fix] - follow 및 프로필 리뷰 데이터 불러오기 test 중
  database.types.ts
  next.config.mjs
  src/app/(nonAuth)/join/page.tsx
  src/app/(nonAuth)/login/page.tsx
  src/app/page.tsx
  src/components/LogOut.tsx
  src/components/ProfileReview.tsx
  src/components/TodoBar.tsx
  src/components/TodoCard.tsx
  src/shared/store.ts
Labels: bug, documentation, enhancement

#101 [fix] - todo 수정 취소 되지 않는 오류 수정 #100
  src/app/(auth)/layout.tsx
  src/app/(nonAuth)/layout.tsx
  src/components/FindPassword/PasswordPotal.tsx
  src/components/NewTodo.tsx
  src/components/TodoModal/TodoDetail.tsx
Labels: bug, documentation, enhancement

#105 [fix] - follow 구현 중, 우선 db엔 반영됨
  database.types.ts
  src/components/FollowBtn.tsx
  src/components/TodoCard.tsx
  src/types/type.ts
Labels: documentation, enhancement

#106 [fix] - main page async 삭제, follow btn 숨김
  src/app/page.tsx
  src/components/FollowBtn.tsx
  src/components/TodoCard.tsx
  src/components/TodoModal/CommentForm.tsx
Labels: bug, documentation

#109 [feat/#108] - 새 글 등록시 파일 미첨부 알림, 투두 카드 이미지 크기 고정, 로그인 비밀번호 숨김
  package-lock.json
  src/app/(nonAuth)/login/page.tsx
  src/app/page.tsx
  src/components/NewTodo.tsx
  src/components/TodoBar.tsx
  src/components/TodoCard.tsx
  yarn.lock
Labels: bug, documentation, enhancement

#111 [fix,style/#110] 데이터 불러오지 못하는 오류 해결 및 마이페이지 css
  src/app/(nonAuth)/layout.tsx
  src/app/page.tsx
  src/components/ProfileContents.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileReview.tsx
  src/components/ProfileReviewLike.tsx
  src/supabase/myPage/profileImage.ts
  src/types/type.ts
Labels: bug, documentation, enhancement

#113 [style] - 메인페이지, 피드페이지, nav CSS 수정
  src/app/(auth)/mypage/page.tsx
  src/app/page.tsx
  src/assets/FF3.jpg
  src/components/AllCard.tsx
  src/components/Calendar.tsx
  src/components/FindPassword/PasswordModal.tsx
  src/components/LikeTop.tsx
  src/components/MainCard.tsx
  src/components/NavBar.tsx
  src/components/NewCard.tsx
  src/components/NewTodo.tsx
  src/components/TodoList.tsx
  src/components/TodoModal/CommentForm.tsx
  src/components/TodoModal/TodoDetail.tsx
  src/components/TodoModal/TodoModal.tsx
Labels: documentation

#117 [style/#116] 마이페이지 css
  src/app/(auth)/mypage/page.tsx
  src/components/Calendar.tsx
  src/components/ProfileContents.tsx
  src/components/ProfileImage.tsx
  src/components/ProfileReview.tsx
  src/components/ProfileReviewLike.tsx
Labels: bug, documentation, enhancement

#119 [style] - 마이페이지 CSS 및 버튼들 애니메이션 추가
  src/app/(auth)/mypage/page.tsx
  src/components/Calendar.tsx
  src/components/LogOut.tsx
  src/components/NewTodo.tsx
  src/components/ProfileContents.tsx
  src/components/ProfileReview.tsx
  src/components/ProfileReviewLike.tsx
  src/components/TodoCard.tsx
  src/components/TodoList.tsx
Labels: documentation

#121 [feat/#120] 마이페이지 - 밀려진 코드 복구 수정기능 확보
  src/components/ProfileContents.tsx
  src/components/ProfileImage.tsx
  src/supabase/myPage/profileImage.ts
Labels: bug, documentation, enhancement

#122 [build] - 배포용 최종 빌드
  src/components/TodoModal/CommentForm.tsx
  src/components/TodoModal/TodoDetail.tsx
Labels: documentation

#124 [fix/#123] - 로그인 페이지 로딩화면 추가
  src/app/(auth)/layout.tsx
  src/app/(nonAuth)/layout.tsx
Labels: documentation
